### ISSUE TITLE
A config of time for fake player persistent

### ISSUE THREAD

**Issue by SettingDust** [henkelmax/persistent-players#1]
**Is your feature request related to a problem? Please describe.**

- [ ] A config of time for fake player persistent.
- [ ] Maybe you can add config such as mobList and targetRange for mobs to attack fakes?
- [ ] ~~Don't spawn fakes when there is no player in server~~ 

**Describe the solution you'd like**
A cache set(such as caffeine?) saved fake players. Remove it when timeout

**Comment by henkelmax** [comment]
> A config of time for fake player persistent.

What do you mean with this?

> Don't spawn fakes when there is no player in server

Why?

**Comment by SettingDust** [comment]
@henkelmax 
Fakes can disappear after configurable time.

Removed, useless

**Comment by henkelmax** [comment]
>  Fakes can disappear after configurable time.

Would make no sense, because where should the player be spawned if he logs back in?

> Maybe you can add config such as mobList and targetRange for mobs to attack fakes?

Unfortunately that is not possible, because I would have to change every mobs AI tasks to attack the offline player that is considered a neutral mob.

**Comment by SettingDust** [comment]
> 
> Would make no sense, because where should the player be spawned if he logs back in?

Save the position?

> Unfortunately that is not possible, because I would have to change every mobs AI tasks to attack the offline player that is considered a neutral mob.

Just set target after fake spawned?
