### ISSUE TITLE
Persistent Players In version 1.12.2 Error  Failed to find persisted player. Defaulting to vanilla spawning.

### ISSUE THREAD

**Issue by kisshack123** [henkelmax/persistent-players#4]
I play mod Persistent Players In version 1.12.2
forge 1.12.2-forge-14.23.5.2854 
I find it doesnt mod work 
I think it might work on in server 
I found a message on the CMDServer saying
[22:03:41] [Server thread/ERROR] [persistent_players]: Failed to find persisted player. Defaulting to vanilla spawning.
[latest.log](https://github.com/henkelmax/persistent-players/files/6411473/latest.log)

1. Go to RUN Server 1.12.2
2. Click on 'logs'
3. Scroll down to 'latest'
4. See error[23:24:42] [Server thread/ERROR] [persistent_players]: Failed to find persisted player. Defaulting to vanilla spawning.
**Expected behavior**
When a player leaves the game, there should be The body is in the game but does not have it.
I don't want the playersTo escape from the game suddenly
It's a very nice MOD, I hope you will fix it.
I want to use it on my server. And I will give you credit.

**Versions**
- Minecraft version 1.12.2
- Forge version 1.12.2-forge-14.23.5.2854 
- Mod version [1.12.2] Persistent Players 1.12.2-1.0.2

**Other mods**
No other mods

**Comment by henkelmax** [comment]
I'm sorry, but this version isn't supported anymore.
