### ISSUE TITLE
Version Update (1.19+)

### ISSUE THREAD

**Issue by wizcreations7** [henkelmax/persistent-players#8]
I hope this message finds you well. I am a fan of Persistent Players for Minecraft and have been using it for some time now. I wanted to reach out to you and see if there are any plans to update the mod for Minecraft version 1.19 or newer.

I'm sure you are aware that the latest versions of Minecraft include many new features and changes that make the game even more enjoyable to play. I, and many other players, would love to be able to use your mod in these latest versions. We've been hindered by the version of this mod for a while, as we consider it essential.

If you have plans to update the mod, could you please provide an estimated timeline or any information you can share about the update? I understand that modding can be a time-consuming and challenging process, and I appreciate all the hard work you have done so far, whether it be this mod or another.

Thank you for your time and consideration, and I look forward to hearing back from you soon.

**Comment by henkelmax** [comment]
There are no plans on updating the mod in any way, sorry.

**Comment by wizcreations7** [comment]
> There are no plans on updating the mod in any way, sorry.

Alrighty! I just wanted to reach out and see. Would you be open to the possibility of someone else contributing and/or forking the mod to provide this update?

**Comment by henkelmax** [comment]
Yeah I would be open for that.
